version: "3"

services:
    web:
        build: ./web
        ports:
            - 8080:8080
        volumes:
            - ./web:/app
            - /app/node_modules
        networks:
            - main
    api:
        build: ./api
        ports:
            - 8081:8081
        volumes:
            - ./api:/home/zafer/api
        networks:
            - main

networks:
    main:
        driver: bridge
